services:
  app:
    build:
      context: .
    command: /app/tokei-api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - KEMAL_ENV=development
      - TEMP_DIR=/tmp/tokei-api
      - CACHE_DB_PATH=/tmp/tokei-api/tokei-api.sqlite3
      - RETENTION_DAYS=7
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - ./spec:/app/spec
      - ./shard.yml:/app/shard.yml
      - ./shard.lock:/app/shard.lock
      - ./.env:/app/.env
    restart: unless-stopped
